CREATE TABLE IF NOT EXISTS users(
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(40) NOT NULL,
  password VARCHAR(20) NOT NULL,
  email VARCHAR(40) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS decks(
  id UUID PRIMARY kEY DEFAULT gen_random_uuid(),
  created_by UUID NOT NULL REFERENCES users(id),
  name VARCHAR(30) NOT NULL,
  cards INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cards(
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  deck UUID NOT NULL REFERENCES decks(id),
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  type VARCHAR(20) NOT NULL DEFAULT 'general',
  is_flipped BOOLEAN NOT NULL DEFAULT FALSE,
  tags TEXT[] NULL,
  step VARCHAR(15) NOT NULL DEFAULT 'learning',
  ease_factor NUMERIC NOT NULL DEFAULT 2.5,
  repetition_number SMALLINT NOT NULL DEFAULT 0,
  interval TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);